name: aqueduct_2
version: 1.0.0
description: A modern HTTP server application framework, ORM and OAuth2 provider with OpenAPI 3.0 integration. Foundation for REST, RPC or GraphQL services.
author: DISCO Open Source <support@discoos.org>
homepage: https://github.com/DISCOOS/aqueduct-2

environment:
  sdk: ">=2.0.0 <3.0.0"

# Change when IPR is resolved with Stable/Kernel
publish_to: none

dependencies:
  args: ^1.5.0
  crypto: ^2.0.6
  logging: ^1.0.1
  meta: ^1.1.5
  open_api: ^2.0.1
  password_hash: ^2.0.0
  path: ^1.6.1
  postgres: ^2.1.1
  pub_cache: ^0.2.3
  runtime_2: ^1.0.0
  safe_config_2: ^1.0.0
  isolate_executor_2: ^1.0.0

dependency_overrides:
  safe_config_2:
    git: https://github.com/DISCOOS/safe-config-2.git
  runtime_2:
    git: https://github.com/DISCOOS/dart-runtime-2.git
  isolate_executor_2:
    git: https://github.com/DISCOOS/dart-isolate-executor-2.git

dev_dependencies:
  matcher: '>=0.12.3 <0.14.0'
  test: ^1.3.0
  http: ^0.13.1
  aqueduct_test:
    path: ../aqueduct_test

executables:
  aqueduct_2: aqueduct_2