name: aqueduct_test
description: Utilities for writing automated tests for Aqueduct applications
version: 1.0.0
author: DISCO Open Source <support@discoos.org>
homepage: https://github.com/DISCOOS/aqueduct-2

environment:
  sdk: ">=2.0.0 <3.0.0"

publish_to: none

dependencies:
  test: ^1.3.0
  matcher: '>=0.12.3 <0.14.0'

# This is removed before being published.
dependency_overrides:
  aqueduct_2:
    path: ../aqueduct

