name: wildfire
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

publish_to: none

dependencies:
  aqueduct_2: ^1.0.0
  safe_config_2:
    git:
      url: https://github.com/DISCOOS/safe-config-2.git
      ref: master
  runtime_2:
    git:
      url: https://github.com/DISCOOS/dart-runtime-2.git
      ref: master
  isolate_executor_2:
    git:
      url: https://github.com/DISCOOS/dart-isolate-executor-2
      ref: master

dependency_overrides:
  aqueduct_2:
    path: ../..

dev_dependencies:
  test: ^1.0.0
  aqueduct_test:
    path: ../../../aqueduct_test
